(define (problem Nasa_strips_advanced_model_prob01)
(:domain Nasa_strips_advanced_model_withSoftConstraints)
(:objects
        CrewMember-1 CrewMember-2 CrewMember-3 CrewMember-4 - crew
        breakfast breakfast2 normalwork1 normalwork2 dinner meditation sleep lunch loading unloading treadmill exercise_bike mutationexp xrayexp communication xrayexp2 communication2 takephoto repairshuttle repairshuttle2 repairshuttle3 repairshuttle01 repairshuttle02 repairshuttle03 massSpectrometry_EXP01 massSpectrometry_EXP02 massSpectrometry_EXP03 massSpectrometry_EXP04 Advanced_Diagnostic_Ultrasound_in_Microgravity APCF_Crystal_Growth CBTM CBTM2 CubeRRt CyclopsDemo rearrange_Spectrometer - activity
        locA locB locC locD locE locF - location
)
(:init
    (=(rem_time_today_forall)40)
    (=(rem_time_today CrewMember-1)10)
    (=(rem_time_today CrewMember-2)10)
    (=(rem_time_today CrewMember-3)10)
    (=(rem_time_today CrewMember-4)10)
    (useonlyonceforcleanup)
    (spectrometerarranged)
    (=(decreaseintime)2)
    (=(revecountcannotbeusedtill)0)
    (=(cannotbeusedtill)4)
    (=(number_of_crew_members breakfast)0)
    (=(number_of_crew_members breakfast2)0)	
    (=(number_of_crew_members normalwork1)0)
    (=(number_of_crew_members normalwork2)0)
    (=(number_of_crew_members dinner)0)
    (=(number_of_crew_members meditation)0)
    (=(number_of_crew_members sleep)0)
    (=(number_of_crew_members lunch)0)
    (=(number_of_crew_members loading)0)
    (=(number_of_crew_members unloading)0)
    (=(number_of_crew_members treadmill)0)
    (=(number_of_crew_members exercise_bike)0)
    (=(number_of_crew_members takephoto)0)
    (=(number_of_crew_members repairshuttle)0)
    (=(number_of_crew_members repairshuttle2)0)
    (=(number_of_crew_members repairshuttle3)0)
    (=(number_of_crew_members repairshuttle03)0)
    (=(number_of_crew_members repairshuttle01)0)
    (=(number_of_crew_members repairshuttle02)0)
    (=(number_of_crew_members xrayexp)0)
    (=(number_of_crew_members communication)0)
    (=(number_of_crew_members xrayexp2)0)
    (=(number_of_crew_members communication2)0)
    (=(number_of_crew_members massSpectrometry_EXP01)0)
    (=(number_of_crew_members massSpectrometry_EXP02)0)
    (=(number_of_crew_members massSpectrometry_EXP03)0)
    (=(number_of_crew_members massSpectrometry_EXP04)0)
    (=(number_of_crew_members rearrange_Spectrometer)0)
    (=(number_of_crew_members Advanced_Diagnostic_Ultrasound_in_Microgravity)0)
    (=(number_of_crew_members APCF_Crystal_Growth)0)
    (=(number_of_crew_members CBTM)0)
    (=(number_of_crew_members CBTM2)0)
    (=(number_of_crew_members CubeRRt)0)
    (=(number_of_crew_members CyclopsDemo)0)
     
    (latch_open)
    ;;(=(max_crewmember_for_activity breakfast)0)
    ;;(=(max_crewmember_for_activity breakfast2)0)
    (=(max_crewmember_for_activity normalwork1)2)
    (=(max_crewmember_for_activity normalwork2)2)
    ;;(=(max_crewmember_for_activity dinner)0)
    (=(max_crewmember_for_activity meditation)2)
    (=(max_crewmember_for_activity sleep)2)
    (=(max_crewmember_for_activity lunch)2)
    (=(max_crewmember_for_activity loading)2)
    (=(max_crewmember_for_activity unloading)2)
    (=(max_crewmember_for_activity treadmill)1)
    (=(max_crewmember_for_activity exercise_bike)1)
    (=(max_crewmember_for_activity takephoto)2)
    (=(max_crewmember_for_activity repairshuttle)2)
    (=(max_crewmember_for_activity repairshuttle2)2)
    (=(max_crewmember_for_activity repairshuttle3)1)
    (=(max_crewmember_for_activity repairshuttle03)3)
    (=(max_crewmember_for_activity repairshuttle01)2)
    (=(max_crewmember_for_activity repairshuttle02)2)
    (=(max_crewmember_for_activity xrayexp)3)
    (=(max_crewmember_for_activity communication)3)
    (=(max_crewmember_for_activity xrayexp2)1)
    (=(max_crewmember_for_activity communication2)1)
    (=(max_crewmember_for_activity massSpectrometry_EXP01)2)
    (=(max_crewmember_for_activity massSpectrometry_EXP02)1)
    (=(max_crewmember_for_activity massSpectrometry_EXP03)3)
    (=(max_crewmember_for_activity massSpectrometry_EXP04)2)
    (=(max_crewmember_for_activity rearrange_Spectrometer)4)
    (=(max_crewmember_for_activity Advanced_Diagnostic_Ultrasound_in_Microgravity)2)
    (=(max_crewmember_for_activity APCF_Crystal_Growth)3)
    (=(max_crewmember_for_activity CBTM)1)
    (=(max_crewmember_for_activity CBTM2)2)
    (=(max_crewmember_for_activity CubeRRt)2)
    (=(max_crewmember_for_activity CyclopsDemo)2)


    (typeofactivitynormal breakfast)
    (typeofactivitynormal normalwork1)
    (typeofactivitynormal normalwork2)
    (typeofactivitynormal dinner)
    (typeofactivitynormal meditation)
    (typeofactivitynormal sleep)
    (typeofactivitynormal lunch)
    (typeofactivitynormal loading)
    (typeofactivitynormal unloading)
    (typeofactivitynormal treadmill)
    (typeofactivitynormal exercise_bike)
    (typeofactivitytakephoto takephoto)
    (typeofactivitynormal repairshuttle)
    (typeofactivitynormal repairshuttle01)
    (typeofactivitynormal xrayexp)
    (typeofactivitytype01 communication)
    (typeofactivitynormal xrayexp2)
    (typeofactivitytype01 communication2)
    (typeofactivitytype02 breakfast2)
    (typeofactivitytype02 repairshuttle2)
    (typeofactivitytype02 repairshuttle3)
    (typeofactivitytype02 repairshuttle02)
    (typeofactivitytype02 repairshuttle03)
    (typeofactivitytypeSpectrometry massSpectrometry_EXP01)
    (typeofactivitytypeSpectrometry massSpectrometry_EXP02)
    (typeofactivitytypeSpectrometry massSpectrometry_EXP03)
    (typeofactivitytypeSpectrometry massSpectrometry_EXP04)
    (typeofactivitytypeRearrangeSpectrometer rearrange_Spectrometer)
    (typeofactivitytype01 Advanced_Diagnostic_Ultrasound_in_Microgravity)
    (typeofactivitytype02 APCF_Crystal_Growth)
    (typeofactivitynormal CBTM)
    (typeofactivitynormal CBTM2)
    (typeofactivitynormal CubeRRt)
    (typeofactivitynormal CyclopsDemo)

	    
    (currentcrewmember CrewMember-1)
    (inordercrew CrewMember-1 CrewMember-2)
    (inordercrew CrewMember-2 CrewMember-3)
    (inordercrew CrewMember-3 CrewMember-4)
    (inordercrew CrewMember-4 CrewMember-1)

)


(:goal(and(daycompleted)(activitycompleted massSpectrometry_EXP01)(activitycompleted massSpectrometry_EXP02)
)

)

)
;;(activitycompleted lunch)(activitycompleted CBTM)(activitycompleted CBTM2)(activitycompleted CubeRRt)(activitycompleted Advanced_Diagnostic_Ultrasound_in_Microgravity)(activitycompleted treadmill)