(define (problem Nasa_strips_advanced_model_prob01)
(:domain Nasa_strips_advanced_model_withSoftConstraints)
(:objects
        CrewMember-1 CrewMember-2 CrewMember-3 CrewMember-4 - crew
        breakfast breakfast2 normalwork1 normalwork2 dinner meditation sleep lunch loading unloading treadmill exercise_bike mutationexp xrayexp communication xrayexp2 communication2 takephoto repairshuttle repairshuttle2 repairshuttle3 repairshuttle01 repairshuttle02 repairshuttle03 massSpectrometry_room01 massSpectrometry_room02 massSpectrometry_room03 massSpectrometry_room04 Advanced_Diagnostic_Ultrasound_in_Microgravity APCF_Crystal_Growth CBTM CBTM2 CubeRRt CyclopsDemo - activity
        locA locB locC locD locE locF - location
)
(:init   
    (=(rem_time_today CrewMember-2)2)
    (=(rem_time_today CrewMember-1)2)
    (=(rem_time_today CrewMember-3)2)
    (=(rem_time_today CrewMember-4)2)
    (=(crewmemberswithcompletedwork)0)
    (=(remlocationtime locA)10)
    (=(remlocationtime locB)10)
    (=(remlocationtime locC)10)
    (=(remlocationtime locD)10)
    (=(remlocationtime locE)10)
    (=(remlocationtime locF)10)
    ; (=(recentlyusedcrewtime CrewMember-1)0)
    ; (=(recentlyusedcrewtime CrewMember-2)0)
    ; (=(recentlyusedcrewtime CrewMember-3)0)
    ; (=(recentlyusedcrewtime CrewMember-4)0)
    ; (=(recentlyusedlocationtime locA)0)
    ; (=(recentlyusedlocationtime locB)0)
    ; (=(recentlyusedlocationtime locC)0)
    ; (=(recentlyusedlocationtime locD)0)
    ; (=(recentlyusedlocationtime locE)0)
    ; (=(recentlyusedlocationtime locF)0)
    (=(slottime)4)
    (=(currentslotphase)0)
    (=(rem_time_today_all)8)
    (=(total_number_crew)4)
    (=(number_of_crew_members breakfast)0)
    (=(number_of_crew_members breakfast2)0)	
    (=(number_of_crew_members normalwork1)0)
    (=(number_of_crew_members normalwork2)0)
    (=(number_of_crew_members dinner)0)
    (=(number_of_crew_members meditation)0)
    (=(number_of_crew_members sleep)0)
    (=(number_of_crew_members lunch)0)
    (=(number_of_crew_members loading)0)
    (=(number_of_crew_members unloading)0)
    (=(number_of_crew_members treadmill)0)
    (=(number_of_crew_members exercise_bike)0)
    (=(number_of_crew_members takephoto)0)
    (=(number_of_crew_members repairshuttle)0)
    (=(number_of_crew_members repairshuttle2)0)
    (=(number_of_crew_members repairshuttle3)0)
    (=(number_of_crew_members repairshuttle03)0)
    (=(number_of_crew_members repairshuttle01)0)
    (=(number_of_crew_members repairshuttle02)0)
    (=(number_of_crew_members xrayexp)0)
    (=(number_of_crew_members communication)0)
    (=(number_of_crew_members xrayexp2)0)
    (=(number_of_crew_members communication2)0)
    (=(number_of_crew_members massSpectrometry_room01)0)
    (=(number_of_crew_members massSpectrometry_room02)0)
    (=(number_of_crew_members massSpectrometry_room03)0)
    (=(number_of_crew_members massSpectrometry_room04)0)
    (=(number_of_crew_members Advanced_Diagnostic_Ultrasound_in_Microgravity)0)
    (=(number_of_crew_members APCF_Crystal_Growth)0)
    (=(number_of_crew_members CBTM)0)
    (=(number_of_crew_members CBTM2)0)
    (=(number_of_crew_members CubeRRt)0)
    (=(number_of_crew_members CyclopsDemo)0)

    (=(currentactivitytime breakfast)0)
    (=(currentactivitytime breakfast2)0)	
    (=(currentactivitytime normalwork1)0)
    (=(currentactivitytime normalwork2)0)
    (=(currentactivitytime dinner)0)
    (=(currentactivitytime meditation)0)
    (=(currentactivitytime sleep)0)
    (=(currentactivitytime lunch)0)
    (=(currentactivitytime loading)0)
    (=(currentactivitytime unloading)0)
    (=(currentactivitytime treadmill)0)
    (=(currentactivitytime exercise_bike)0)
    (=(currentactivitytime takephoto)0)
    (=(currentactivitytime repairshuttle)0)
    (=(currentactivitytime repairshuttle2)0)
    (=(currentactivitytime repairshuttle3)0)
    (=(currentactivitytime repairshuttle03)0)
    (=(currentactivitytime repairshuttle01)0)
    (=(currentactivitytime repairshuttle02)0)
    (=(currentactivitytime xrayexp)0)
    (=(currentactivitytime communication)0)
    (=(currentactivitytime xrayexp2)0)
    (=(currentactivitytime communication2)0)
    (=(currentactivitytime massSpectrometry_room01)0)
    (=(currentactivitytime massSpectrometry_room02)0)
    (=(currentactivitytime massSpectrometry_room03)0)
    (=(currentactivitytime massSpectrometry_room04)0)
    (=(currentactivitytime Advanced_Diagnostic_Ultrasound_in_Microgravity)0)
    (=(currentactivitytime APCF_Crystal_Growth)0)
    (=(currentactivitytime CBTM)0)
    (=(currentactivitytime CBTM2)0)
    (=(currentactivitytime CubeRRt)0)
    (=(currentactivitytime CyclopsDemo)0)

    (latch_open)
    (=(max_crewmember_for_activity breakfast)2)
    (=(max_crewmember_for_activity breakfast2)2)
    (=(max_crewmember_for_activity normalwork1)2)
    (=(max_crewmember_for_activity normalwork2)2)
    (=(max_crewmember_for_activity dinner)2)
    (=(max_crewmember_for_activity meditation)2)
    (=(max_crewmember_for_activity sleep)2)
    (=(max_crewmember_for_activity lunch)2)
    (=(max_crewmember_for_activity loading)2)
    (=(max_crewmember_for_activity unloading)2)
    (=(max_crewmember_for_activity treadmill)1)
    (=(max_crewmember_for_activity exercise_bike)1)
    (=(max_crewmember_for_activity takephoto)2)
    (=(max_crewmember_for_activity repairshuttle)2)
    (=(max_crewmember_for_activity repairshuttle2)2)
    (=(max_crewmember_for_activity repairshuttle3)1)
    (=(max_crewmember_for_activity repairshuttle03)3)
    (=(max_crewmember_for_activity repairshuttle01)2)
    (=(max_crewmember_for_activity repairshuttle02)2)
    (=(max_crewmember_for_activity xrayexp)3)
    (=(max_crewmember_for_activity communication)3)
    (=(max_crewmember_for_activity xrayexp2)1)
    (=(max_crewmember_for_activity communication2)1)
    (=(max_crewmember_for_activity massSpectrometry_room01)2)
    (=(max_crewmember_for_activity massSpectrometry_room02)1)
    (=(max_crewmember_for_activity massSpectrometry_room03)3)
    (=(max_crewmember_for_activity massSpectrometry_room04)2)
    (=(max_crewmember_for_activity Advanced_Diagnostic_Ultrasound_in_Microgravity)2)
    (=(max_crewmember_for_activity APCF_Crystal_Growth)3)
    (=(max_crewmember_for_activity CBTM)1)
    (=(max_crewmember_for_activity CBTM2)2)
    (=(max_crewmember_for_activity CubeRRt)2)
    (=(max_crewmember_for_activity CyclopsDemo)2)


    (=(decreaseintime breakfast)2)
    (=(decreaseintime breakfast2)2)	
    (=(decreaseintime normalwork1)2)
    (=(decreaseintime normalwork2)2)
    (=(decreaseintime dinner)2)
    (=(decreaseintime meditation)2)
    (=(decreaseintime sleep)2)
    (=(decreaseintime lunch)2)
    (=(decreaseintime loading)2)
    (=(decreaseintime unloading)2)
    (=(decreaseintime treadmill)2)
    (=(decreaseintime exercise_bike)2)
    (=(decreaseintime takephoto)2)
    (=(decreaseintime repairshuttle)2)
    (=(decreaseintime repairshuttle2)2)
    (=(decreaseintime repairshuttle3)2)
    (=(decreaseintime repairshuttle03)2)
    (=(decreaseintime repairshuttle01)2)
    (=(decreaseintime repairshuttle02)2)
    (=(decreaseintime xrayexp)2)
    (=(decreaseintime communication)2)
    (=(decreaseintime xrayexp2)2)
    (=(decreaseintime communication2)2)
    (=(decreaseintime massSpectrometry_room01)2)
    (=(decreaseintime massSpectrometry_room02)2)
    (=(decreaseintime massSpectrometry_room03)2)
    (=(decreaseintime massSpectrometry_room04)2)
    (=(decreaseintime Advanced_Diagnostic_Ultrasound_in_Microgravity)2)
    (=(decreaseintime APCF_Crystal_Growth)2)
    (=(decreaseintime CBTM)2)
    (=(decreaseintime CBTM2)2)
    (=(decreaseintime CubeRRt)2)
    (=(decreaseintime CyclopsDemo)2)
    ; (=(check)0)


    (typeofactivitynormal breakfast)
    (typeofactivitynormal normalwork1)
    (typeofactivitynormal normalwork2)
    (typeofactivitynormal dinner)
    (typeofactivitynormal meditation)
    (typeofactivitynormal sleep)
    (typeofactivitynormal lunch)
    (typeofactivitynormal loading)
    (typeofactivitynormal unloading)
    (typeofactivitynormal treadmill)
    (typeofactivitynormal exercise_bike)
    (typeofactivitynormal takephoto)
    (typeofactivitynormal repairshuttle)
    (typeofactivitynormal repairshuttle01)
    (typeofactivitynormal xrayexp)
    (typeofactivitynormal communication)
    (typeofactivitynormal xrayexp2)
    (typeofactivitynormal communication2)
    (typeofactivitynormal breakfast2)
    (typeofactivitynormal repairshuttle2)
    (typeofactivitynormal repairshuttle3)
    (typeofactivitynormal repairshuttle02)
    (typeofactivitynormal repairshuttle03)
    (typeofactivitynormal massSpectrometry_room01)
    (typeofactivitynormal massSpectrometry_room02)
    (typeofactivitynormal massSpectrometry_room03)
    (typeofactivitynormal massSpectrometry_room04)
    (typeofactivitynormal Advanced_Diagnostic_Ultrasound_in_Microgravity)
    (typeofactivitynormal APCF_Crystal_Growth)
    (typeofactivitynormal CBTM)
    (typeofactivitynormal CBTM2)
    (typeofactivitynormal CubeRRt)
    (typeofactivitynormal CyclopsDemo)


)


(:goal(and(=(rem_time_today_all)0))				


)

)
