(define (problem Nasa_strips_advanced_model_prob01)
(:domain Nasa_strips_advanced_model_withSoftConstraints)
(:objects
        CrewMember-1 CrewMember-2 CrewMember-3 CrewMember-4 - crew
        breakfast breakfast2 normalwork1 normalwork2 dinner meditation sleep lunch loading unloading t1exercise t2exercise mutationexp xrayexp communication xrayexp2 communication2 takephoto repairshuttle repairshuttle2 repairshuttle3 repairshuttle01 repairshuttle02 repairshuttle03 massSpectrometrycab01 massSpectrometrycab02 massSpectrometrycab03 massSpectrometrycab04 - activity
        locA locB locC locD locE locF - location
)
(:init
    (=(rem_time_today_forall)40)
    (=(rem_time_today CrewMember-1)10)
    (=(rem_time_today CrewMember-2)10)
    (=(rem_time_today CrewMember-3)10)
    (=(rem_time_today CrewMember-4)10)
    (useonlyonceforcleanup)
    (=(decreaseintime)2)
    (=(revecountcannotbeusedtill)0)
    (=(cannotbeusedtill)4)
    (=(number_of_crew_members breakfast)0)
    (=(number_of_crew_members breakfast2)0)	
    (=(number_of_crew_members normalwork1)0)
    (=(number_of_crew_members normalwork2)0)
    (=(number_of_crew_members dinner)0)
    (=(number_of_crew_members meditation)0)
    (=(number_of_crew_members sleep)0)
    (=(number_of_crew_members lunch)0)
    (=(number_of_crew_members loading)0)
    (=(number_of_crew_members unloading)0)
    (=(number_of_crew_members t1exercise)0)
    (=(number_of_crew_members t2exercise)0)
    (=(number_of_crew_members takephoto)0)
    (=(number_of_crew_members repairshuttle)0)
    (=(number_of_crew_members repairshuttle2)0)
    (=(number_of_crew_members repairshuttle3)0)
    (=(number_of_crew_members repairshuttle03)0)
    (=(number_of_crew_members repairshuttle01)0)
    (=(number_of_crew_members repairshuttle02)0)
    (=(number_of_crew_members xrayexp)0)
    (=(number_of_crew_members communication)0)
    (=(number_of_crew_members xrayexp2)0)
    (=(number_of_crew_members communication2)0)
    (=(number_of_crew_members massSpectrometrycab01)0)
    (=(number_of_crew_members massSpectrometrycab02)0)
    (=(number_of_crew_members massSpectrometrycab03)0)
    (=(number_of_crew_members massSpectrometrycab04)0)
     
   ;;(latch_open)
    (=(max_crewmember_for_activity breakfast)2)
    (=(max_crewmember_for_activity breakfast2)2)
    (=(max_crewmember_for_activity normalwork1)2)
    (=(max_crewmember_for_activity normalwork2)2)
    (=(max_crewmember_for_activity dinner)4)
    (=(max_crewmember_for_activity meditation)2)
    (=(max_crewmember_for_activity sleep)2)
    (=(max_crewmember_for_activity lunch)2)
    (=(max_crewmember_for_activity loading)2)
    (=(max_crewmember_for_activity unloading)2)
    (=(max_crewmember_for_activity t1exercise)2)
    (=(max_crewmember_for_activity t2exercise)2)
    (=(max_crewmember_for_activity takephoto)2)
    (=(max_crewmember_for_activity repairshuttle)2)
    (=(max_crewmember_for_activity repairshuttle2)2)
    (=(max_crewmember_for_activity repairshuttle3)1)
    (=(max_crewmember_for_activity repairshuttle03)3)
    (=(max_crewmember_for_activity repairshuttle01)2)
    (=(max_crewmember_for_activity repairshuttle02)2)
    (=(max_crewmember_for_activity xrayexp)3)
    (=(max_crewmember_for_activity communication)3)
    (=(max_crewmember_for_activity xrayexp2)1)
    (=(max_crewmember_for_activity communication2)1)
    (=(max_crewmember_for_activity massSpectrometrycab01)2)
    (=(max_crewmember_for_activity massSpectrometrycab02)1)
    (=(max_crewmember_for_activity massSpectrometrycab03)3)
    (=(max_crewmember_for_activity massSpectrometrycab04)2)


    (typeofactivitynormal breakfast)
    (typeofactivitynormal normalwork1)
    (typeofactivitynormal normalwork2)
    (typeofactivitynormal dinner)
    (typeofactivitynormal meditation)
    (typeofactivitynormal sleep)
    (typeofactivitynormal lunch)
    (typeofactivitynormal loading)
    (typeofactivitynormal unloading)
    (typeofactivitynormal t1exercise)
    (typeofactivitynormal t2exercise)
    (typeofactivitynormal takephoto)
    (typeofactivitynormal repairshuttle)
    (typeofactivitynormal repairshuttle01)
    (typeofactivitynormal xrayexp)
    (typeofactivitytype01 communication)
    (typeofactivitynormal xrayexp2)
    (typeofactivitytype01 communication2)
    (typeofactivitytype02 breakfast2)
    (typeofactivitytype02 repairshuttle2)
    (typeofactivitytype02 repairshuttle3)
    (typeofactivitytype02 repairshuttle02)
    (typeofactivitytype02 repairshuttle03)
    (typeofactivitytype01 massSpectrometrycab01)
    (typeofactivitytype01 massSpectrometrycab02)
    (typeofactivitytype01 massSpectrometrycab03)
    (typeofactivitytype01 massSpectrometrycab04)

	    
    (currentcrewmember CrewMember-1)
    (inordercrew CrewMember-1 CrewMember-2)
    (inordercrew CrewMember-2 CrewMember-3)
    (inordercrew CrewMember-3 CrewMember-4)
    (inordercrew CrewMember-4 CrewMember-1)

)


(:goal(and(daycompleted)
)

)

)
